### ISSUE TITLE
Kernel Problems (Staging/lineage-17.1)

### ISSUE THREAD

**Issue by ghost** [DevelopedInside/android_kernel_wileyfox_msm8937#7]
The changes to the staging Kernel are most welcome there are a few that mention LED's is this meant to fix the led not working?
The updated boot.img still bootloops no idea why? nikith290 rom, boot.img still works.

The changes to the Kernel, today, Fixes the bootloops but it never completes boot. Again using nikith290 rom, boot.img still works.

**Comment by uixdess** [comment]
Hello!

As you can see the kernel is still in the branch staging, so it maybe unstable or not bootable.

What do you mean by this?

> The changes to the Kernel, today, Fixes the bootloops but it never completes boot.

**Comment by ghost** [comment]
The Phone appears to boot and the boot animation appears and stays there as though the phone is booting but it never gets to the sign in screen even after half an hour.

**Comment by uixdess** [comment]
> The Phone appears to boot and the boot animation appears and stays there as though the phone is booting but it never gets to the sign in screen even after half an hour.

Then where is logs? Try look at the logs and you will see what's wrong

**Comment by ghost** [comment]
[dmesg.log](https://github.com/DevelopedInside/android_kernel_wileyfox_msm8937/files/4944813/dmesg.log)
File above for when it does not boot
[dmesg-booting.log](https://github.com/DevelopedInside/android_kernel_wileyfox_msm8937/files/4944815/dmesg-booting.log)

**Comment by uixdess** [comment]
Why do you share recovery log?
Today did test build with kernel and it booted

**Comment by uixdess** [comment]
![IMG_20200720_222331_967](https://user-images.githubusercontent.com/53017714/87977630-bb74e100-cad7-11ea-92e0-474e2e03050f.jpg)

**Comment by ghost** [comment]
Yes it now boots Thank you
